<?php
/**
 * Integration
 *
 * @category    Interactiv4
 * @package     Interactiv4_Integration
 * @copyright   Copyright (c) 2013 Interactiv4 SL. (http://www.interactiv4.com)
 */
?>
<?php
$_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid();

$_colspan = 3;
if (!$this->_addAfter) {
    $_colspan -= 1;
}
$_colspan = $_colspan > 1 ? 'colspan="' . $_colspan . '"' : '';
?>
<?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
<div class="grid" id="grid<?php echo $_htmlId; ?>">
    <table cellpadding="0" cellspacing="0" class="border">
        <tbody>
            <tr class="headings">
<?php foreach ($this->_columns as $columnName => $column):?>
                <th><?php echo $column['label'] ?></th>
<?php endforeach;?>
            </tr>
            <?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
            <tr id="headings<?php echo $_htmlId ?>">
                <td>
                    <input type="text" style="width:280px" class="input-text" value="Website" disabled="disabled" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/website_remote'); ?>" name="groups[mapper_in][fields][website_remote][value]" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/website_position'); ?>" name="groups[mapper_in][fields][website_position][value]" />
                </td>
            </tr>
            
             <?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
            <tr id="headings<?php echo $_htmlId ?>">
                <td>
                    <input type="text" style="width:280px" class="input-text" value="Storeview" disabled="disabled" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/storeview_remote'); ?>" name="groups[mapper_in][fields][storeview_remote][value]" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/storeview_position'); ?>" name="groups[mapper_in][fields][storeview_position][value]" />
                </td>
            </tr>
            
            
            <?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
            <tr id="headings<?php echo $_htmlId ?>">
                <td>
                    <input type="text" style="width:280px" class="input-text" value="Price" disabled="disabled" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/price_remote'); ?>" name="groups[mapper_in][fields][price_remote][value]" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/price_position'); ?>" name="groups[mapper_in][fields][price_position][value]" />
                </td>
            </tr>
            <?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
            <tr id="headings<?php echo $_htmlId ?>">
                <td>
                    <input type="text" style="width:280px" class="input-text" value="SKU" disabled="disabled" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/sku_remote'); ?>" name="groups[mapper_in][fields][sku_remote][value]" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/sku_position'); ?>" name="groups[mapper_in][fields][sku_position][value]" />
                </td>
            </tr>
            <?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
            <tr id="headings<?php echo $_htmlId ?>">
                <td>
                    <input type="text" style="width:280px" class="input-text" value="Special Price" disabled="disabled" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/special_price_remote'); ?>" name="groups[mapper_in][fields][special_price_remote][value]" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/special_price_position'); ?>" name="groups[mapper_in][fields][special_price_position][value]" />
                </td>
            </tr>
            
            <?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
            <tr id="headings<?php echo $_htmlId ?>">
                <td>
                    <input type="text" style="width:280px" class="input-text" value="Special Price From Date" disabled="disabled" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/special_price_from_remote'); ?>" name="groups[mapper_in][fields][special_price_from_remote][value]" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/special_price_from_position'); ?>" name="groups[mapper_in][fields][special_price_from_position][value]" />
                </td>
            </tr>
            
            <?php $_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid(); ?>
            <tr id="headings<?php echo $_htmlId ?>">
                <td>
                    <input type="text" style="width:280px" class="input-text" value="Special Price To Date" disabled="disabled" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/special_price_to_remote'); ?>" name="groups[mapper_in][fields][special_price_to_remote][value]" />
                </td>
                <td>
                    <input type="text" style="width:100px" class="input-text" value="<?php echo Mage::app()->getStore()->getConfig('i4sync_price/mapper_in/special_price_to_position'); ?>" name="groups[mapper_in][fields][special_price_to_position][value]" />
                </td>
            </tr>
        </tbody>
    </table>
</div>
